# Oppo 2013
add_lunch_combo probam_find5-userdebug
# Xperia 2013
##Board: Fusion3
add_lunch_combo probam_yuga-userdebug
add_lunch_combo probam_odin-userdebug
add_lunch_combo probam_pollux_windy-userdebug
add_lunch_combo probam_pollux-userdebug
# Xperia 2012
##Board: Blue
add_lunch_combo probam_mint-userdebug
add_lunch_combo probam_hayabusa-userdebug
add_lunch_combo probam_tsubasa-userdebug
##Board: Montblanc
add_lunch_combo probam_kumquat-userdebug
add_lunch_combo probam_lotus-userdebug
add_lunch_combo probam_nypon-userdebug
add_lunch_combo probam_pepper-userdebug
# Xperia 2011
##Board: Mogami
add_lunch_combo probam_anzu-userdebug
add_lunch_combo probam_coconut-userdebug
add_lunch_combo probam_haida-userdebug
add_lunch_combo probam_hallon-userdebug
add_lunch_combo probam_iyokan-userdebug
add_lunch_combo probam_mango-userdebug
add_lunch_combo probam_satsuma-userdebug
add_lunch_combo probam_smultron-userdebug
add_lunch_combo probam_urushi-userdebug
##Board: Zeus
add_lunch_combo probam_zeus-userdebug
# Samsung 2011
add_lunch_combo probam_captivatemtd-userdebug
add_lunch_combo probam_fascinatemtd-userdebug
add_lunch_combo probam_galaxysmtd-userdebug
add_lunch_combo probam_i9100-userdebug
add_lunch_combo probam_i9103-userdebug
add_lunch_combo probam_i9100g-userdebug
add_lunch_combo probam_i927-userdebug
add_lunch_combo probam_d710-userdebug
add_lunch_combo probam_p1-userdebug
# Samsung 2012
add_lunch_combo probam_hercules-userdebug
add_lunch_combo probam_skyrocket-userdebug
add_lunch_combo probam_p5100-userdebug
add_lunch_combo probam_p5110-userdebug
add_lunch_combo probam_p3100-userdebug
add_lunch_combo probam_p3110-userdebug
# Nexus Devices
add_lunch_combo probam_toro-userdebug
add_lunch_combo probam_mako-userdebug
add_lunch_combo probam_maguro-userdebug
add_lunch_combo probam_manta-userdebug
add_lunch_combo probam_crespo-userdebug
add_lunch_combo probam_grouper-userdebug
add_lunch_combo probam_tilapia-userdebug
add_lunch_combo probam_toroplus-userdebug
# HTC Rezound
add_lunch_combo probam_vigor-userdebug
# HTC Shooter
add_lunch_combo probam_shooter-userdebug
add_lunch_combo probam_shootervm-userdebug
add_lunch_combo probam_shooteru-userdebug
# HTC 2011
add_lunch_combo probam_ace-userdebug
add_lunch_combo probam_saga-userdebug
add_lunch_combo probam_vivo-userdebug
add_lunch_combo probam_runnymede-userdebug
# HTC 2013
add_lunch_combo probam_fireball-userdebug
add_lunch_combo probam_jewel-userdebug
add_lunch_combo probam_evita-userdebug
add_lunch_combo probam_ville-userdebug
add_lunch_combo probam_m7-userdebug
add_lunch_combo probam_m7ul-userdebug
add_lunch_combo probam_m7att-userdebug
add_lunch_combo probam_m7wls-userdebug
# Samsung 2010
add_lunch_combo probam_epicmtd-userdebug
# Samsung 2013
add_lunch_combo probam_d2att-userdebug
add_lunch_combo probam_d2cri-userdebug
add_lunch_combo probam_d2mtr-userdebug
add_lunch_combo probam_d2spr-userdebug
add_lunch_combo probam_d2tmo-userdebug
add_lunch_combo probam_d2usc-userdebug
add_lunch_combo probam_d2vzw-userdebug
add_lunch_combo probam_i605-userdebug
add_lunch_combo probam_i9300-userdebug
add_lunch_combo probam_i9305-userdebug
add_lunch_combo probam_jflteatt-userdebug
add_lunch_combo probam_jfltecan-userdebug
add_lunch_combo probam_jfltecri-userdebug
add_lunch_combo probam_jfltecsp-userdebug
add_lunch_combo probam_jfltespr-userdebug
add_lunch_combo probam_jfltetmo-userdebug
add_lunch_combo probam_jflteusc-userdebug
add_lunch_combo probam_jfltevzw-userdebug
add_lunch_combo probam_jfltexx-userdebug
add_lunch_combo probam_l900-userdebug
add_lunch_combo probam_t0lte-userdebug
add_lunch_combo probam_t0lteatt-userdebug
add_lunch_combo probam_n7000-userdebug
add_lunch_combo probam_n7100-userdebug
add_lunch_combo probam_venturi_usa-userdebug
add_lunch_combo probam_ypg1-userdebug
# Samsung & LGE Legacy Devices
add_lunch_combo probam_gio-userdebug
add_lunch_combo probam_cooper-userdebug
add_lunch_combo probam_p500-userdebug
add_lunch_combo probam_tass-userdebug
add_lunch_combo probam_beni-userdebug
add_lunch_combo probam_p990-userdebug
add_lunch_combo probam_p920-userdebug
add_lunch_combo probam_p970-userdebug
# HTC One V
add_lunch_combo probam_primoc-userdebug
add_lunch_combo probam_primou-userdebug
# LGE
add_lunch_combo probam_p880-userdebug
add_lunch_combo probam_p930-userdebug
add_lunch_combo probam_su640-userdebug
add_lunch_combo probam_vs920-userdebug
# Motorola 2013
add_lunch_combo probam_edison-userdebug
add_lunch_combo probam_mb886-userdebug
add_lunch_combo probam_vanquish-userdebug
add_lunch_combo probam_spyder-userdebug
add_lunch_combo probam_targa-userdebug
add_lunch_combo probam_maserati-userdebug
add_lunch_combo probam_umts_spyder-userdebug
add_lunch_combo probam_solana-userdebug
add_lunch_combo probam_vanquishgsm-userdebug
add_lunch_combo probam_scorpionmini-userdebug
add_lunch_combo probam_xt907-userdebug
add_lunch_combo probam_xt926-userdebug
add_lunch_combo probam_xt925-userdebug
add_lunch_combo probam_xt897-userdebug
add_lunch_combo probam_xt897c-userdebug
# Asus device
add_lunch_combo probam_tf300t-userdebug
add_lunch_combo probam_tf201-userdebug
# Amazon
add_lunch_combo probam_otter-userdebug
add_lunch_combo probam_otter2-userdebug
add_lunch_combo probam_tate-userdebug
add_lunch_combo probam_jem-userdebug
# HTC-legacy
add_lunch_combo probam_marvel-userdebug
add_lunch_combo probam_villec2-userdebug
add_lunch_combo probam_endeavoru_userdebug
